import { OAuthProvider } from './types.js';

/**
 * Anthropic Claude OAuth provider configuration
 *
 * Uses Claude Code CLI setup tokens for Claude Pro/Max subscription access.
 * Setup tokens are generated by the official Claude Code CLI and work as
 * standard Anthropic API keys.
 *
 * Flow:
 * 1. User runs `claude setup-token` (official CLI)
 * 2. Authenticates via browser to claude.ai
 * 3. CLI returns long-lived setup token (sk-ant-oat01-...)
 * 4. Token is used with api.anthropic.com as x-api-key header
 *
 * No client_id required - tokens are pre-authenticated by Claude Code CLI
 */
export const ANTHROPIC_PROVIDER: OAuthProvider = {
  name: 'anthropic',
  displayName: 'Anthropic Claude',
  clientId: '', // Public OAuth - no client_id needed
  authorizationEndpoint: 'https://claude.ai/oauth/authorize',
  tokenEndpoint: 'https://claude.ai/oauth/token',
  scopes: [], // No scopes needed for public flow
  supportsRefresh: true,
};

/**
 * Get provider configuration by name
 */
export function getProvider(name: string): OAuthProvider | null {
  switch (name.toLowerCase()) {
    case 'anthropic':
    case 'claude':
      return ANTHROPIC_PROVIDER;
    default:
      return null;
  }
}

/**
 * List all available providers
 */
export function listProviders(): OAuthProvider[] {
  return [ANTHROPIC_PROVIDER];
}

/**
 * Check if provider is configured
 */
export function isProviderConfigured(provider: OAuthProvider): boolean {
  // For Anthropic's public OAuth flow, client_id is not required
  // Only check that endpoints are configured
  return (
    provider.authorizationEndpoint !== '' &&
    provider.tokenEndpoint !== ''
  );
}
